### ISSUE TITLE
投票失败，报错[25018]

### ISSUE THREAD

**Issue by HellSakura** [dd178/BILI_judgement#1]
<img width="584" alt="截屏2021-10-16 上午10 53 37" src="https://user-images.githubusercontent.com/43169031/137571036-6ea1aadd-c8eb-4252-ba12-9d30bc3867a1.png">

**Comment by dd178** [comment]
试一下新版本，我这边测试没问题，但是我获取的案件很少，测试不够严谨

**Comment by HellSakura** [comment]
> 试一下新版本，我这边测试没问题，但是我获取的案件很少，测试不够严谨

等明天我试一下，今天的我手动做完了

**Comment by ADJazzzz** [comment]
> 试一下新版本，我这边测试没问题，但是我获取的案件很少，测试不够严谨

我这里案件数正常

**Comment by HellSakura** [comment]
> > 试一下新版本，我这边测试没问题，但是我获取的案件很少，测试不够严谨
> 
> 等明天我试一下，今天的我手动做完了
<img width="762" alt="截屏2021-10-17 上午11 23 44" src="https://user-images.githubusercontent.com/43169031/137609644-4eedc1f5-b889-4ae7-a2bf-b02cf372c572.png">
没有问题了，只是偶然还会出现此错误，目前20次只出现了一次，不影响完成
