### ISSUE TITLE
我的SESSDATA里面带逗号然后说cookie失效

### ISSUE THREAD

**Issue by YinBuLiao** [dd178/BILI_judgement#10]
我的SESSDATA里面带逗号然后说cookie失效
![image](https://user-images.githubusercontent.com/35324248/155278690-0b251432-0368-44f8-86d6-8c700a819fb3.png)

**Comment by dd178** [comment]
你在哪抓的？

**Comment by YinBuLiao** [comment]
首页nav

**Comment by YinBuLiao** [comment]
另一个号也是在首页nav抓的那个就没有逗号就可以用

**Comment by dd178** [comment]
逗号替换成%2C试试

**Comment by YinBuLiao** [comment]
解决了
