### ISSUE TITLE
投票模式可否加入参考别人观点的轮询查询和别人观点数量大于一定数量才参考?

### ISSUE THREAD

**Issue by FairyWorld** [dd178/BILI_judgement#11]
- config.json的模式2为"获取案件后有观点就参考观点，没有就先暂存案件id跳过，等案件池空了获取不到观点后再倒回去投默认"
- 有可能投票时间过短或者案件池空了后，容易在别人还没有观点时投设置的默认观点
- 建议在模式2的基础上加入模式4
    1. 等案件池空了每隔半分钟或者自定义时长查询一次是否有观点, 直到10分钟或自定义时长还是没有观点则投上默认的观点, 然后退出
    2. 根据别人观点投票只有在别人观点数大于3条或者自定义条数后才执行, 否则就先跳过然后等案件池空了在轮询一段时间别人的观点直到大于指定条数才投, 超时则选择默认。
    3. 如果在轮询获取观点期间案件被别人投满了，导致案件失效则获取新的案件执行

**Comment by suir1** [comment]
附议，多参考几个观点比较好，只参考一个有时候直接就打差了。而且触发关键词就打差太绝对了，大多数打普通比较恰当

**Comment by Suplinna** [comment]
嘿嘿，瓜子花生大杏仁大佬的PR通过了，现在是按最多观点投票了 @PeanutMelonSeedBigAlmond 大佬tql，不过最后加的那条if：如果环境是windows，则按任意键退出，我在电脑上运行完20次投票后日志出现了这个提示，但是按任何键盘按键他并不退出，程序始终在那挂着，需要手动终止关闭，不知道这条功能有什么意义，我是自己将这段代码替换成了原代码的最后一段，对比一下应该相当于把这小段if语句删除了，就正常运行和自动退出了，我的环境是win10，py3.10

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 嘿嘿，瓜子花生大杏仁大佬的PR通过了，现在是按最多观点投票了 @PeanutMelonSeedBigAlmond 大佬tql，不过最后加的那条if：如果环境是windows，则按任意键退出，我在电脑上运行完20次投票后日志出现了这个提示，但是按任何键盘按键他并不退出，程序始终在那挂着，需要手动终止关闭，不知道这条功能有什么意义，我是自己将这段代码替换成了原代码的最后一段，对比一下应该相当于把这小段if语句删除了，就正常运行和自动退出了，我的环境是win10，py3.10

在我这没有问题，环境：Windows10，Python3.9

我一般按的是回车，不知道是不是这个问题

**Comment by Suplinna** [comment]
> > 嘿嘿，瓜子花生大杏仁大佬的PR通过了，现在是按最多观点投票了 @PeanutMelonSeedBigAlmond 大佬tql，不过最后加的那条if：如果环境是windows，则按任意键退出，我在电脑上运行完20次投票后日志出现了这个提示，但是按任何键盘按键他并不退出，程序始终在那挂着，需要手动终止关闭，不知道这条功能有什么意义，我是自己将这段代码替换成了原代码的最后一段，对比一下应该相当于把这小段if语句删除了，就正常运行和自动退出了，我的环境是win10，py3.10
> 
> 在我这没有问题，环境：Windows10，Python3.9
> 
> 我一般按的是回车，不知道是不是这个问题

嗷，我不需要这个功能，剔除这段让他运行完自己终止了，用着也挺好，提出来也是如果有别的同学和我一样遇上这个问题的可以参考着解决，谢谢花生大佬和作者大佬的贡献~

**Comment by dd178** [comment]
> 嘿嘿，瓜子花生大杏仁大佬的PR通过了，现在是按最多观点投票了 @PeanutMelonSeedBigAlmond 大佬tql，不过最后加的那条if：如果环境是windows，则按任意键退出，我在电脑上运行完20次投票后日志出现了这个提示，但是按任何键盘按键他并不退出，程序始终在那挂着，需要手动终止关闭，不知道这条功能有什么意义，我是自己将这段代码替换成了原代码的最后一段，对比一下应该相当于把这小段if语句删除了，就正常运行和自动退出了，我的环境是win10，py3.10

删掉也无所谓，本来就是为了适配打包exe的，不过现在应该已经修复了

**Comment by Suplinna** [comment]
> > 嘿嘿，瓜子花生大杏仁大佬的PR通过了，现在是按最多观点投票了 @PeanutMelonSeedBigAlmond 大佬tql，不过最后加的那条if：如果环境是windows，则按任意键退出，我在电脑上运行完20次投票后日志出现了这个提示，但是按任何键盘按键他并不退出，程序始终在那挂着，需要手动终止关闭，不知道这条功能有什么意义，我是自己将这段代码替换成了原代码的最后一段，对比一下应该相当于把这小段if语句删除了，就正常运行和自动退出了，我的环境是win10，py3.10
> 
> 删掉也无所谓，本来就是为了适配打包exe的，不过现在应该已经修复了

了解！
