### ISSUE TITLE
关于 Cookie 失效问题

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [dd178/BILI_judgement#15]
现在的 Cookie 有效期似乎只有 3 天，超过之后如果不更新将会无法投票

是否考虑加入自动刷新 Cookie 的逻辑（或者已经有了）？

**Comment by KudouRan** [comment]
如果能够自动刷新再好不过了，但目前据我观察，cookie 应该是需要用户主动刷新才失效的（后台不会短时间内立即失效）。


一个正常使用的浏览器应该会去主动刷新 cookie（发现了疑是刷新的请求，但是不小心清掉了），如果从不常用的浏览器或者私密窗口登录并获取 cookie 可能不会那么快就失效。

**Comment by Suplinna** [comment]
是否可能加入账号密码登陆方式呢？代码开源且本地运行的话，账号密码登陆安全性应该也有保障？

**Comment by KudouRan** [comment]
> 是否可能加入账号密码登陆方式呢？代码开源且本地运行的话，账号密码登陆安全性应该也有保障？

账号密码有时有人机验证，需要点击文字或者滑动图片

**Comment by Suplinna** [comment]
> > 是否可能加入账号密码登陆方式呢？代码开源且本地运行的话，账号密码登陆安全性应该也有保障？
> 
> 账号密码有时有人机验证，需要点击文字或者滑动图片

了解了

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 现在的 Cookie 有效期似乎只有 3 天，超过之后如果不更新将会无法投票
> 
> 是否考虑加入自动刷新 Cookie 的逻辑（或者已经有了）？

经过数周观察后发现，似乎只有把cookie换到新的环境运行才会导致cookie失效（比如在本地获取了cookie之后，把脚本云服务器运行）

具体情况有待进一步验证
