### ISSUE TITLE
ssl should be SSLContext, bool, Fingerprint or None, got False instead

### ISSUE THREAD

**Issue by WernerHai** [dd178/BILI_judgement#21]
[ERROR]: 登录验证id为【67143131】的账户失败，原因为【ssl should be SSLContext, bool, Fingerprint or None, got False instead.】，跳过此账户后续操作
请问这是什么问题呢？（腾讯云国内服务器，centos7.9，python3.11）
把文件拉到本地window正常运行（windows10，python3.11）

**Comment by dd178** [comment]
我在官方的python3.11 docker镜像中测试了一下，并未复现错误，你试试降低python版本运行，因为我看aiohttp说对3.11兼容性不是很好，或者使用docker容器运行

**Comment by WernerHai** [comment]
谢谢，改用python3.10成功运行了
