### ISSUE TITLE
是否考虑加入按比例随机投票的功能

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [dd178/BILI_judgement#3]
我的想法是，为了更真实的模拟人工操作，我自己做了个程序统计了最近一定数量的案例中，各个选项的选择人数

![image](https://user-images.githubusercontent.com/25266280/138491210-5d778d97-46ec-4291-b8ba-a5fdc3e6f1c0.png)

是否可以按照这个比例来进行随机投票，以更好的模拟人工投票概率？

我不是很会用Python

**Comment by dd178** [comment]
以前确实考虑过投票前先拉取以往案件的投票结果来预测，但是感觉太麻烦没做，有需要可以手动设置投票比例， `"vote": [0, 1, 2]` 表示三种投票类型比例为1：1：1，`"vote": [0, 0, 1, 2]`表示2：1：1，投票是从列表里随机选取的，填的数量越多，抽到的概率也就越大。谁要做可以pr

**Comment by PeanutMelonSeedBigAlmond** [comment]
我这里倒是有一个现成的程序，可以将案件的投情况结果计算出来并输出为json，不过我是用`kotlin`写的，还没有想到如何和这个项目配合使用

目前唯一能想到的就是这个项目(`BILI_Judgement`)读取生成的json，解析出比例之后按比例投票

可以将程序部署在coding上，利用coding CI实现定时抓取比例的功能

唯一的缺点是会增大本项目的耦合性

**Comment by PeanutMelonSeedBigAlmond** [comment]
Update:

![image](https://user-images.githubusercontent.com/25266280/148793804-98bdcfd0-5ee2-44d2-8c45-04cd4faedd2f.png)

感觉阿b是要铁了心把脚本干掉

from: [cv14783000](https://www.bilibili.com/read/cv14783000)

**Comment by dd178** [comment]
> Update:
> 
> ![image](https://user-images.githubusercontent.com/25266280/148793804-98bdcfd0-5ee2-44d2-8c45-04cd4faedd2f.png)
> 
> 感觉阿b是要铁了心把脚本干掉
> 
> from: [cv14783000](https://www.bilibili.com/read/cv14783000)

看了，白嫖大会员的途径又少一个

**Comment by PeanutMelonSeedBigAlmond** [comment]
没办法了，看来也只能手动投票了，也不知道什么时候实装、规则是什么 

从 Windows 版邮件发送

发件人: 178
发送时间: 2022年1月11日 0:25
收件人: dd178/BILI_judgement
抄送: 花生瓜子大杏仁; Author
主题: Re: [dd178/BILI_judgement] 是否考虑加入按比例随机投票的功能 (Issue #3)

Update:

感觉阿b是要铁了心把脚本干掉
from: cv14783000
看了，白嫖大会员的途径又少一个

**Comment by Suplinna** [comment]
![image](https://user-images.githubusercontent.com/51396970/149331353-cd1ab289-12a2-4576-aa6d-91291683ce2c.png)
钓鱼题用作者大大脚本跟着投应该也不会错，这个验证码属实麻烦，目前还在开发，还没有实装，不知道验证码会是啥样的，到时候老哥看看有没有可能也给破了[手动滑稽] @dd178

**Comment by PeanutMelonSeedBigAlmond** [comment]
> ![image](https://user-images.githubusercontent.com/51396970/149331353-cd1ab289-12a2-4576-aa6d-91291683ce2c.png) 钓鱼题用作者大大脚本跟着投应该也不会错，这个验证码属实麻烦，目前还在开发，还没有实装，不知道验证码会是啥样的，到时候老哥看看有没有可能也给破了[手动滑稽] @dd178

![image](https://user-images.githubusercontent.com/25266280/149332720-a102334e-584d-4ceb-afad-1830f6583aa9.png)

他直接把观点去掉了……

**Comment by Suplinna** [comment]
> > ![image](https://user-images.githubusercontent.com/51396970/149331353-cd1ab289-12a2-4576-aa6d-91291683ce2c.png) 钓鱼题用作者大大脚本跟着投应该也不会错，这个验证码属实麻烦，目前还在开发，还没有实装，不知道验证码会是啥样的，到时候老哥看看有没有可能也给破了[手动滑稽] @dd178
> 
> ![image](https://user-images.githubusercontent.com/25266280/149332720-a102334e-584d-4ceb-afad-1830f6583aa9.png)
> 
> 他直接把观点去掉了……

老哥你是不是这几天没有使用这个脚本，我这两天还是一直在用这个脚本，准确率还是相当的高，准确率70+，运行的日志也还有 根据XXX的观点为案件投下【中间是空的】 ，我怀疑阿b只是在案件未完成时屏蔽了显示，这个脚本现在仍然可以随机读取到一个案件的评价并跟着投

**Comment by PeanutMelonSeedBigAlmond** [comment]
> > > ![image](https://user-images.githubusercontent.com/51396970/149331353-cd1ab289-12a2-4576-aa6d-91291683ce2c.png) 钓鱼题用作者大大脚本跟着投应该也不会错，这个验证码属实麻烦，目前还在开发，还没有实装，不知道验证码会是啥样的，到时候老哥看看有没有可能也给破了[手动滑稽] @dd178
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/25266280/149332720-a102334e-584d-4ceb-afad-1830f6583aa9.png)
> > 他直接把观点去掉了……
> 
> 老哥你是不是这几天没有使用这个脚本，我这两天还是一直在用这个脚本，准确率还是相当的高，准确率70+，运行的日志也还有 根据XXX的观点为案件投下【中间是空的】 ，我怀疑阿b只是在案件未完成时屏蔽了显示，这个脚本现在仍然可以随机读取到一个案件的评价并跟着投

这两天我是手动投的，因为我是想看看触发了验证码是什么情况

另，我看了阿B的接口数据，他只是把Text置空了，但是实际上投票选项代号还是在的，和你说的情况一样

![image](https://user-images.githubusercontent.com/25266280/149334946-64dcd65c-3922-4613-97b9-c662f937863c.png)

**Comment by Suplinna** [comment]
嗯嗯，看这个说法验证码还在开发中，并未实装，暂时应该还看不着，唉，我也很犹豫，想继续用又有点怕[滑稽]钓鱼题应该是不怕的，就看这个验证码了，而且也不一定非要攻克这个验证码，能够做到检测验证码，然后在遇到验证码时候不要重复错误提交，立即中断，再给个大的提醒让操作者去风纪窗口自己把那个验证码过了再重新跑一下脚本（前提是仅关闭验证码窗口不会被判断为未通过，以及出现之后是否会一直留存直到这天结束前能在别的设备处理，具体还得看到时候那个验证码的逻辑），这个验证码看着说法是一天最多遇到一次。实在不行就只能手动提交直到当天遇到验证码之后，剩下的用脚本跑了。
