### ISSUE TITLE
可以正常运行, 但是日志显示有问题

### ISSUE THREAD

**Issue by FairyWorld** [dd178/BILI_judgement#7]
我是使用青龙运行项目的, 运行过程中的日志全部都是 "成功根据【在下柠檬精o】的观点为案件【AC1nx411c7k7】投下【】"，没有显示出投下的是什么只有一个括号。
![image](https://user-images.githubusercontent.com/32956212/147810543-67e90667-2857-4ea1-8fe8-8c834cb3376e.png)

**Comment by dd178** [comment]
投票功能是正常的，不影响使用，这是因为之前b站返回的观点数据是这样的` {"vote": 11,"vote_text": "好"}`，现在变成这样` {"vote": 11,"vote_text": ""}`了，vote_text变成空字符串自然也就读取不到投下什么票了
