### ISSUE TITLE
Cannot connect to host api.bilibili.com:443 ssl:False [Name or service not known]

### ISSUE THREAD

**Issue by TTNTO** [dd178/BILI_judgement#8]
在本地运行无任何异常，但是放到百度云服务器(debian 10)上时不时的会报这个错误，不知道作者能不能提供点解决思路呢
![vps-error](https://user-images.githubusercontent.com/50487449/150460390-7f6a1d99-b74f-4e80-8cf5-aa0675bba71f.png)

**Comment by dd178** [comment]
看上去像dns问题
