### ISSUE TITLE
【讨论】关于B站防脚本策略具体规则与应对方法

### ISSUE THREAD

**Issue by dd178** [dd178/BILI_judgement#9]
各位有什么想法或者关于风控的规则可以发上来一起讨论，另外，建议大家停用脚本一段时间，b站开始拉黑脚本了，等摸清楚b站风控策略之后再启用。
>4：近期我们上线了防脚本策略。对于多次触发防脚本策略的风纪委员进行人工审核后，我们找出下列有很大嫌疑使用非正常手段参与投票的风纪委员，并永久拉黑。目前防脚本策略正在优化中，如果有命中的风纪委员认为是误伤，也欢迎到风纪委邮箱进行申诉。

**Comment by cijann** [comment]
首先是随机等待时间吧，运行后随机等待一段时间后再执行后续动作，然后每次投票之间加入随机等待时间

**Comment by Suplinna** [comment]
不知道咱们有没有老哥在名单里躺枪的（应该没有吧） ，目前已知的两个防脚本手段是钓鱼题和验证码，钓鱼题目前来看应该是不用怕的，脚本跟风投应该是不会错，验证码不知道有没有兄弟遇到，具体还得看到时候验证码的判定逻辑：1.验证码脚本可跳。2.验证码较复杂不可跳。可跳就不用多说了，不可跳又分为两种情况：3.验证码刷出来当天就一直存在，使用者可以在看到脚本识别验证码中断后的通知后，手动去处理验证码。4.验证码刷出的当时不能当时正确验证则立即判为错（限定一分钟内或者关闭验证码界面也算错）。第3种情况则设置在发现验证码后立即提醒使用者去手动验证。第4种情况就很难了，基本上全自动脚本就不想了，只希望有个依托油猴的js脚本可以在我点击获取案件之后，自动随机读取一个观点并选择，再自动随机选个是否观看视频，然后自己手动提交选下一个就好了，直到遇到一次验证码之后，剩下的用脚本跑（目前验证码一天最多遇到一次）。

**Comment by Suplinna** [comment]
> 首先是随机等待时间吧，运行后随机等待一段时间后再执行后续动作，然后每次投票之间加入随机等待时间

楼主这个脚本里面是有随机等待时间的，追求稳妥的话可以改一下数值把随机区间调大一点就行，这是小问题

**Comment by dd178** [comment]
大家如果使用电脑浏览器手动做任务的话希望能开着f12来做，帮我抓一下b站防脚本的请求，我一直遇不到

**Comment by FairyWorld** [comment]
> 大家如果使用电脑浏览器手动做任务的话希望能开着f12来做，帮我抓一下b站防脚本的请求，我一直遇不到

今天答完了，暂时没发现有什么特别的钓鱼问题

**Comment by pooneyy** [comment]
三个多月以来，我从未碰到过验证码，也没见到过钓鱼题（可能没认出来）

**Comment by dd178** [comment]
> 三个多月以来，我从未碰到过验证码，也没见到过钓鱼题（可能没认出来）

确实，我也没碰到，不知道是b站唬人的还是没被检测到

**Comment by GamerNoTitle** [comment]
就我自己来说，我用我自己以前做的那个的时候，B站就有一次加入了headers的检验，此后就再也没有什么说封脚本的操作了……
我的那个在这里https://github.com/ElainaMoe/bilibiliJudge
因为之前Github查脚本仓库所以被我移到小号上面去了

**Comment by xiaoxingBBji** [comment]
部署到腾讯云函数可行么?

**Comment by jiucai-captain** [comment]
怎么部署到云函数？能不能出个教程

**Comment by PeanutMelonSeedBigAlmond** [comment]
说起来，在 #13 之后能够选择最多的观点进行投票了，是否可以扩大一下参考观点的数量

我看代码里面现在是`5个`（[代码](https://github.com/dd178/BILI_judgement/blob/master/judgement.py#L163)），正常在B站投票的时候默认显示的是`3个`，但是如果点了下面的*查看更多*按钮会展示`20个`投票

我觉得可以把参考观点数改成20个

**Comment by pooneyy** [comment]
> 怎么部署到云函数？能不能出个教程

云函数似乎不支持。我尝试在云函数上运行，aiohttp 模块导入的时候总是出错

**Comment by GamerNoTitle** [comment]
> > 怎么部署到云函数？能不能出个教程
> 
> 云函数似乎不支持。我尝试在云函数上运行，aiohttp 模块导入的时候总是出错

其实你把需要的那些模块在pypi下载以后上传上去是可以用的，只是比较麻烦

**Comment by PeanutMelonSeedBigAlmond** [comment]
我记得似乎是可以直接在云函数控制台直接`pip install aiohttp`就行的，只要执行一次

**Comment by pooneyy** [comment]
> 我记得似乎是可以直接在云函数控制台直接`pip install aiohttp`就行的，只要执行一次

我已经在阿里云和腾讯云上试过了，各种报错：
> module 'typing' has no attribute 'NoReturn'

日志：
```
START RequestId: fc04fe2c-b96d-4f1a-9768-9c9013ccbca3Init Report RequestId: fc04fe2c-b96d-4f1a-9768-9c9013ccbca3 Coldstart: 523ms (PullCode: 182ms InitRuntime: 4ms InitFunction: 337ms) Memory: 128MB MemUsage: 13.60MBERROR RequestId: fc04fe2c-b96d-4f1a-9768-9c9013ccbca3 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):
  File "/var/runtime/python3/bootstrap.py", line 133, in init_handler
    func_handler = get_func_handler(file.rsplit(".", 1)[0], func)
  File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler
    mod = imp.load_module(mname, *imp.find_module(mname))
  File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/user/judgement.py", line 12, in <module>
    import aiohttp
  File "/var/user/aiohttp/__init__.py", line 5, in <module>
    from . import hdrs as hdrs
  File "/var/user/aiohttp/hdrs.py", line 13, in <module>
    from typing_extensions import Final
  File "/var/user/typing_extensions.py", line 141, in <module>
    NoReturn = typing.NoReturn
AttributeError: module 'typing' has no attribute 'NoReturn'", "statusCode": 443}END RequestId: fc04fe2c-b96d-4f1a-9768-9c9013ccbca3Report RequestId: fc04fe2c-b96d-4f1a-9768-9c9013ccbca3 Duration: 0ms Memory: 128MB MemUsage: 13.60MBSTART RequestId:fc04fe2c-b96d-4f1a-9768-9c9013ccbca3
ERROR RequestId:fc04fe2c-b96d-4f1a-9768-9c9013ccbca3 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/judgement.py\", line 12, in \u003cmodule\u003e\n    import aiohttp\n  File \"/var/user/aiohttp/__init__.py\", line 5, in \u003cmodule\u003e\n    from . import hdrs as hdrs\n  File \"/var/user/aiohttp/hdrs.py\", line 13, in \u003cmodule\u003e\n    from typing_extensions import Final\n  File \"/var/user/typing_extensions.py\", line 141, in \u003cmodule\u003e\n    NoReturn = typing.NoReturn\nAttributeError: module 'typing' has no attribute 'NoReturn'","statusCode":443}
END RequestId:fc04fe2c-b96d-4f1a-9768-9c9013ccbca3
Report RequestId:fc04fe2c-b96d-4f1a-9768-9c9013ccbca3 Duration:0ms Memory:128MB MemUsage:0.000000MB
```

**Comment by GamerNoTitle** [comment]
部署之前的终端跟部署后的环境不是一个环境 这样装是没啥用的

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 部署之前的终端跟部署后的环境不是一个环境 这样装是没啥用的

云函数的nodejs环境可以这样装依赖，Python我没试过，明天尝试一下

**Comment by GamerNoTitle** [comment]
如果真的想用云函数的话就得像这样放（这里拿我的一个项目举例子了）
红框框里面就是我这个项目用到的轮子
![image](https://user-images.githubusercontent.com/28426291/166924758-1fbea7c2-b461-478a-aaf2-5904c509f402.png)

**Comment by GamerNoTitle** [comment]
一般来说把whl文件按压缩文件方式打开，把里面的文件夹都上传就能引用到了，但是有些区分Windows和Linux的库要记得下载Linux版本的
![image](https://user-images.githubusercontent.com/28426291/166924987-882dbd75-1af1-4e58-9549-4484cdef299e.png)

**Comment by pooneyy** [comment]
> 如果真的想用云函数的话就得像这样放（这里拿我的一个项目举例子了） 红框框里面就是我这个项目用到的轮子 ![image](https://user-images.githubusercontent.com/28426291/166924758-1fbea7c2-b461-478a-aaf2-5904c509f402.png)

我安装了啊。

![image](https://user-images.githubusercontent.com/85266337/166925304-eb8e8c8f-9f3f-406c-95fa-4fe4c2f37bb5.png)

**Comment by PeanutMelonSeedBigAlmond** [comment]
@pooneyy 看你上面的日志，貌似和aiohttp库关系不大

**Comment by pooneyy** [comment]
> 部署之前的终端跟部署后的环境不是一个环境 这样装是没啥用的

我说的出错是aiohttp出错，aiohttp是已经安装了的，你可以看我的日志内容：
![image](https://user-images.githubusercontent.com/85266337/166925905-511dbff0-90d4-4754-bef0-b3f4b7988f78.png)

**Comment by pooneyy** [comment]
> @pooneyy 看你上面的日志，貌似和aiohttp库关系不大

那是哪里出的问题呀？typing_extensions.py是安装aiohttp的时候附带的

**Comment by PeanutMelonSeedBigAlmond** [comment]
@pooneyy 我已经解决了，除了要手动安装依赖以外，还要在代码里面把配置文件的位置改掉

具体在[此处](https://github.com/dd178/BILI_judgement/blob/master/judgement.py#L196..L197)，将这个改成相对路径就行了

![image](https://user-images.githubusercontent.com/25266280/167211494-1bbfea85-82db-4e96-8a8e-f08f5edfc035.png)

效果

![image](https://user-images.githubusercontent.com/25266280/167211669-7afd4734-613a-4ff4-bfe0-097d55a9c48a.png)

---

附上打包好的依赖，将这里面的文件放进去就行了，**云函数python版本3.7，不保证其他版本可用**

[depenedncies.zip](https://github.com/dd178/BILI_judgement/files/8643440/depenedncies.zip)

**Comment by pooneyy** [comment]
> @pooneyy 我已经解决了，除了要手动安装依赖以外，还要在代码里面把配置文件的位置改掉
> 
> 具体在[此处](https://github.com/dd178/BILI_judgement/blob/master/judgement.py#L196..L197)，将这个改成相对路径就行了
> 
> ![image](https://user-images.githubusercontent.com/25266280/167211494-1bbfea85-82db-4e96-8a8e-f08f5edfc035.png)
> 
> 效果
> 
> ![image](https://user-images.githubusercontent.com/25266280/167211669-7afd4734-613a-4ff4-bfe0-097d55a9c48a.png)
> 
> 附上打包好的依赖，将这里面的文件放进去就行了，**云函数python版本3.7，不保证其他版本可用**
> 
> [depenedncies.zip](https://github.com/dd178/BILI_judgement/files/8643440/depenedncies.zip)

不明原因的调用失败：
![image](https://user-images.githubusercontent.com/85266337/167248550-9f823b87-f135-46ed-a6cc-161339739e1a.png)
我把我的Cookie上传之后成这样了

**Comment by pooneyy** [comment]
![image](https://user-images.githubusercontent.com/85266337/167248597-400308ac-1bf2-4ca7-b87c-8ca7d0f10945.png)
python3.7，依赖是上传的那个压缩包

**Comment by PeanutMelonSeedBigAlmond** [comment]
你函数执行时限是不是没改，函数管理 / 函数配置 / 执行超时时间

**Comment by pooneyy** [comment]
> 你函数执行时限是不是没改，函数管理 / 函数配置 / 执行超时时间

感谢您，跑起来了

**Comment by jiucai-captain** [comment]
想看懂你们在聊些什么，我还需要补习哪些知识点?
表示没看懂

**Comment by Cairl** [comment]
> 你函数执行时限是不是没改，函数管理 / 函数配置 / 执行超时时间
![微信截图_20220511124359](https://user-images.githubusercontent.com/20336299/167770825-c3afe571-064a-46ab-ae26-3d4788595744.png)
请问一下这个错误是怎么弄的？

**Comment by PeanutMelonSeedBigAlmond** [comment]
@Cairl 你执行方法填错了

> 两段式格式为"[文件名].[函数名]"，Python，Node.js，PHP 环境时使用，例如 "index.main_handler";

![image](https://user-images.githubusercontent.com/25266280/167982122-dc3aa5b7-2648-4f7c-a13b-194ef3c5d2e5.png)

**Comment by Cairl** [comment]
> @Cairl 你执行方法填错了
> 
> > 两段式格式为"[文件名].[函数名]"，Python，Node.js，PHP 环境时使用，例如 "index.main_handler";
> 
> ![image](https://user-images.githubusercontent.com/25266280/167982122-dc3aa5b7-2648-4f7c-a13b-194ef3c5d2e5.png)

请问这个执行方法我具体该填什么呢？小白不太懂
